/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    content: Content;
    'seo-redirects': SeoRedirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'submission-files': SubmissionFile;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'form-submissions': {
      files: 'submission-files';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    content: ContentSelect<false> | ContentSelect<true>;
    'seo-redirects': SeoRedirectsSelect<false> | SeoRedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'submission-files': SubmissionFilesSelect<false> | SubmissionFilesSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fa' | 'ar-ae') | ('en' | 'fa' | 'ar-ae')[];
  globals: {
    'site-settings': SiteSetting;
    'design-settings': DesignSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'design-settings': DesignSettingsSelect<false> | DesignSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'en' | 'fa' | 'ar-ae';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'seo' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  legacyID?: string | null;
  isPublic?: boolean | null;
  alt: string;
  title?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Localized pages and editorial content rendered from reusable blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content".
 */
export interface Content {
  id: number;
  /**
   * Stable technical identifier. Avoid changing it after publication.
   */
  key: string;
  kind: 'page' | 'service' | 'solution' | 'knowledge' | 'news';
  /**
   * Optional presentation key for site-specific renderers. Generic pages use default.
   */
  templateKey: string;
  isActive?: boolean | null;
  title: string;
  excerpt?: string | null;
  layout?:
    | (
        | {
            enabled?: boolean | null;
            variant?: ('default' | 'simple' | 'centered' | 'split' | 'cards' | 'compact') | null;
            eyebrow?: string | null;
            title: string;
            /**
             * Optional text within the title to emphasize.
             */
            highlight?: string | null;
            body: string;
            primaryCTA?: {
              label?: string | null;
              url?: string | null;
              openInNewTab?: boolean | null;
            };
            secondaryCTA?: {
              label?: string | null;
              url?: string | null;
              openInNewTab?: boolean | null;
            };
            points?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            enabled?: boolean | null;
            variant?: ('default' | 'simple' | 'centered' | 'split' | 'cards' | 'compact') | null;
            eyebrow?: string | null;
            heading: string;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            enabled?: boolean | null;
            variant?: ('default' | 'simple' | 'centered' | 'split' | 'cards' | 'compact') | null;
            eyebrow?: string | null;
            heading: string;
            intro?: string | null;
            items?:
              | {
                  /**
                   * A short text or icon name.
                   */
                  icon?: string | null;
                  title: string;
                  description: string;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            enabled?: boolean | null;
            variant?: ('default' | 'simple' | 'centered' | 'split' | 'cards' | 'compact') | null;
            heading: string;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            enabled?: boolean | null;
            variant?: ('default' | 'simple' | 'centered' | 'split' | 'cards' | 'compact') | null;
            heading: string;
            items?:
              | {
                  quote: string;
                  name: string;
                  role?: string | null;
                  company?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            enabled?: boolean | null;
            variant?: ('default' | 'simple' | 'centered' | 'split' | 'cards' | 'compact') | null;
            eyebrow?: string | null;
            title: string;
            body?: string | null;
            primaryCTA?: {
              label?: string | null;
              url?: string | null;
              openInNewTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            enabled?: boolean | null;
            variant?: ('default' | 'simple' | 'centered' | 'split' | 'cards' | 'compact') | null;
            /**
             * Select the active form displayed in this section.
             */
            form: number | Form;
            eyebrow?: string | null;
            /**
             * Uses the form title when empty.
             */
            heading?: string | null;
            /**
             * Uses the form description when empty.
             */
            intro?: string | null;
            /**
             * Optional context submitted with the form, such as a page or campaign key.
             */
            context?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'form';
          }
      )[]
    | null;
  slug: string;
  /**
   * Locale-relative path without a leading slash. Leave empty only for Home.
   */
  path?: string | null;
  parent?: (number | null) | Content;
  relatedContent?: (number | Content)[] | null;
  seo?: {
    /**
     * Optional search and social title. Keep it descriptive and concise.
     */
    title?: string | null;
    /**
     * Optional search description. Uses the page excerpt when empty.
     */
    description?: string | null;
    /**
     * Advanced: point search engines at another authoritative URL. The page is omitted from the sitemap while an override is enabled.
     */
    canonicalURL?: string | null;
    /**
     * Enable only after reviewing duplicate-content and sitemap consequences.
     */
    canonicalOverrideEnabled?: boolean | null;
    /**
     * Disable to request noindex and remove this page from the sitemap.
     */
    robotsIndex?: boolean | null;
    /**
     * Disable to request that crawlers do not follow links on this page.
     */
    robotsFollow?: boolean | null;
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  searchText?: string | null;
  translationStatus?: ('missing' | 'draft' | 'translated' | 'reviewed' | 'outdated') | null;
  workflowStatus?: ('draft' | 'review' | 'scheduled' | 'published' | 'archived') | null;
  /**
   * Optional source publication date for imported editorial content.
   */
  legacyPublishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  key: string;
  isActive?: boolean | null;
  requiresPrivacyConsent?: boolean | null;
  retentionMonths: number;
  successRedirect?: string | null;
  title: string;
  description?: string | null;
  successMessage: string;
  consentLabel?: string | null;
  fields?:
    | {
        key: string;
        fieldType:
          | 'text'
          | 'textarea'
          | 'email'
          | 'phone'
          | 'number'
          | 'select'
          | 'multi-select'
          | 'radio'
          | 'checkbox'
          | 'date'
          | 'datetime'
          | 'url'
          | 'file'
          | 'hidden';
        required?: boolean | null;
        minValue?: number | null;
        maxValue?: number | null;
        minLength?: number | null;
        maxLength?: number | null;
        pattern?: string | null;
        options?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        label: string;
        placeholder?: string | null;
        helpText?: string | null;
        optionLabels?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-redirects".
 */
export interface SeoRedirect {
  id: number;
  sourceLocale: 'en' | 'fa' | 'ar-ae';
  /**
   * Normalized locale-relative source path.
   */
  sourcePath?: string | null;
  sourceKey: string;
  to: {
    type: 'content' | 'url';
    content?: (number | null) | Content;
    locale?: ('en' | 'fa' | 'ar-ae') | null;
    url?: string | null;
  };
  status: '308' | '307';
  enabled: boolean;
  reason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Form response inbox. Raw submitted values are retained according to the configured retention period.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  legacyID?: string | null;
  form: number | Form;
  files?: {
    docs?: (number | SubmissionFile)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  locale: 'en' | 'fa' | 'ar-ae';
  contactName?: string | null;
  contactPhone?: string | null;
  contactEmail?: string | null;
  company?: string | null;
  requestType?: string | null;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'new' | 'contacted' | 'qualified' | 'closed';
  priority?: ('low' | 'normal' | 'high' | 'urgent') | null;
  assignedTo?: (number | null) | User;
  contactedAt?: string | null;
  sourceURL?: string | null;
  referrer?: string | null;
  consentGiven: boolean;
  consentText?: string | null;
  userAgent?: string | null;
  ipHash?: string | null;
  expiresAt: string;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-files".
 */
export interface SubmissionFile {
  id: number;
  legacyID?: string | null;
  submission: number | FormSubmission;
  originalName: string;
  checksumSHA256: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  legacyID?: string | null;
  actor?: (number | null) | User;
  actorType: string;
  action: string;
  objectType: string;
  objectID: string;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'content';
        value: number | Content;
      } | null)
    | ({
        relationTo: 'seo-redirects';
        value: number | SeoRedirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'submission-files';
        value: number | SubmissionFile;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  legacyID?: T;
  isPublic?: T;
  alt?: T;
  title?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content_select".
 */
export interface ContentSelect<T extends boolean = true> {
  key?: T;
  kind?: T;
  templateKey?: T;
  isActive?: T;
  title?: T;
  excerpt?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              enabled?: T;
              variant?: T;
              eyebrow?: T;
              title?: T;
              highlight?: T;
              body?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                    openInNewTab?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                    openInNewTab?: T;
                  };
              points?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              enabled?: T;
              variant?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              enabled?: T;
              variant?: T;
              eyebrow?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              enabled?: T;
              variant?: T;
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              enabled?: T;
              variant?: T;
              heading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    role?: T;
                    company?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              enabled?: T;
              variant?: T;
              eyebrow?: T;
              title?: T;
              body?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                    openInNewTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              enabled?: T;
              variant?: T;
              form?: T;
              eyebrow?: T;
              heading?: T;
              intro?: T;
              context?: T;
              id?: T;
              blockName?: T;
            };
      };
  slug?: T;
  path?: T;
  parent?: T;
  relatedContent?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalURL?: T;
        canonicalOverrideEnabled?: T;
        robotsIndex?: T;
        robotsFollow?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  searchText?: T;
  translationStatus?: T;
  workflowStatus?: T;
  legacyPublishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-redirects_select".
 */
export interface SeoRedirectsSelect<T extends boolean = true> {
  sourceLocale?: T;
  sourcePath?: T;
  sourceKey?: T;
  to?:
    | T
    | {
        type?: T;
        content?: T;
        locale?: T;
        url?: T;
      };
  status?: T;
  enabled?: T;
  reason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  key?: T;
  isActive?: T;
  requiresPrivacyConsent?: T;
  retentionMonths?: T;
  successRedirect?: T;
  title?: T;
  description?: T;
  successMessage?: T;
  consentLabel?: T;
  fields?:
    | T
    | {
        key?: T;
        fieldType?: T;
        required?: T;
        minValue?: T;
        maxValue?: T;
        minLength?: T;
        maxLength?: T;
        pattern?: T;
        options?: T;
        label?: T;
        placeholder?: T;
        helpText?: T;
        optionLabels?: T;
        enabled?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  legacyID?: T;
  form?: T;
  files?: T;
  locale?: T;
  contactName?: T;
  contactPhone?: T;
  contactEmail?: T;
  company?: T;
  requestType?: T;
  data?: T;
  status?: T;
  priority?: T;
  assignedTo?: T;
  contactedAt?: T;
  sourceURL?: T;
  referrer?: T;
  consentGiven?: T;
  consentText?: T;
  userAgent?: T;
  ipHash?: T;
  expiresAt?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-files_select".
 */
export interface SubmissionFilesSelect<T extends boolean = true> {
  legacyID?: T;
  submission?: T;
  originalName?: T;
  checksumSHA256?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  legacyID?: T;
  actor?: T;
  actorType?: T;
  action?: T;
  objectType?: T;
  objectID?: T;
  before?: T;
  after?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  phone?: string | null;
  email?: string | null;
  customerPortalURL?: string | null;
  externalCheckoutURL?: string | null;
  socialLinks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  address?: string | null;
  locationLabel?: string | null;
  defaultSEOTitle?: string | null;
  defaultSEODescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-settings".
 */
export interface DesignSetting {
  id: number;
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  surface: string;
  foreground: string;
  muted: string;
  radiusSmall?: number | null;
  radiusMedium?: number | null;
  radiusLarge?: number | null;
  containerWidth?: number | null;
  sectionSpacing?: number | null;
  motionEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        title: string;
        description?: string | null;
        /**
         * Leave empty for the home page.
         */
        path?: string | null;
        iconKey?: string | null;
        openInNewTab?: boolean | null;
        enabled?: boolean | null;
        children?:
          | {
              title: string;
              description?: string | null;
              /**
               * Leave empty for the home page.
               */
              path?: string | null;
              iconKey?: string | null;
              openInNewTab?: boolean | null;
              enabled?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        title: string;
        description?: string | null;
        /**
         * Leave empty for the home page.
         */
        path?: string | null;
        iconKey?: string | null;
        openInNewTab?: boolean | null;
        enabled?: boolean | null;
        children?:
          | {
              title: string;
              description?: string | null;
              /**
               * Leave empty for the home page.
               */
              path?: string | null;
              iconKey?: string | null;
              openInNewTab?: boolean | null;
              enabled?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  mobile?:
    | {
        title: string;
        description?: string | null;
        /**
         * Leave empty for the home page.
         */
        path?: string | null;
        iconKey?: string | null;
        openInNewTab?: boolean | null;
        enabled?: boolean | null;
        children?:
          | {
              title: string;
              description?: string | null;
              /**
               * Leave empty for the home page.
               */
              path?: string | null;
              iconKey?: string | null;
              openInNewTab?: boolean | null;
              enabled?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  logo?: T;
  favicon?: T;
  phone?: T;
  email?: T;
  customerPortalURL?: T;
  externalCheckoutURL?: T;
  socialLinks?: T;
  address?: T;
  locationLabel?: T;
  defaultSEOTitle?: T;
  defaultSEODescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-settings_select".
 */
export interface DesignSettingsSelect<T extends boolean = true> {
  primary?: T;
  secondary?: T;
  accent?: T;
  background?: T;
  surface?: T;
  foreground?: T;
  muted?: T;
  radiusSmall?: T;
  radiusMedium?: T;
  radiusLarge?: T;
  containerWidth?: T;
  sectionSpacing?: T;
  motionEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        title?: T;
        description?: T;
        path?: T;
        iconKey?: T;
        openInNewTab?: T;
        enabled?: T;
        children?:
          | T
          | {
              title?: T;
              description?: T;
              path?: T;
              iconKey?: T;
              openInNewTab?: T;
              enabled?: T;
              id?: T;
            };
        id?: T;
      };
  footer?:
    | T
    | {
        title?: T;
        description?: T;
        path?: T;
        iconKey?: T;
        openInNewTab?: T;
        enabled?: T;
        children?:
          | T
          | {
              title?: T;
              description?: T;
              path?: T;
              iconKey?: T;
              openInNewTab?: T;
              enabled?: T;
              id?: T;
            };
        id?: T;
      };
  mobile?:
    | T
    | {
        title?: T;
        description?: T;
        path?: T;
        iconKey?: T;
        openInNewTab?: T;
        enabled?: T;
        children?:
          | T
          | {
              title?: T;
              description?: T;
              path?: T;
              iconKey?: T;
              openInNewTab?: T;
              enabled?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'content';
      value: number | Content;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}